version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: res-menu-db
    environment:
      POSTGRES_DB: res_menu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - res-menu-network

volumes:
  postgres_data:
    name: res-menu-postgres-data

networks:
  res-menu-network:
    name: res-menu-network 