version: '3.8'

services:
  res-menu:
    container_name: res-menu
    image: "ghcr.io/wodyjowski/res-menu:master"
    ports:
      - "80:8080"
      - "443:8080"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=res_menu;Username=postgres;Password=postgres;Port=5432
      - ASPNETCORE_URLS=http://+:8080;https://+:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - res-menu-network

  postgres:
    image: postgres:16-alpine
    container_name: res-menu-db
    environment:
      POSTGRES_DB: res_menu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - res-menu-network

volumes:
  postgres_data:
    name: res-menu-postgres-data

networks:
  res-menu-network:
    name: res-menu-network

